### ISSUE TITLE
DeckArrayManager and Deck (debugging)

### ISSUE THREAD

**Issue by kevinnaruse** [AfterKraft/BlackJack#26]
Gabe, would you mind looking over both these two classes? I defined Card to contain a URL object that corresponds to the cardID , and cardID is the initial placement of the exact card at the initDeck() method. I wanted to make sure I did the url and getResource() method right.
DeckArrayManager  has the arraylist, and I made hand a subclass of deck. it is simply a smaller deck.
Thanks
Kevin

p.s. also I was considering having some word art with fonts that could be placed in the applet panel to communicate to the user. What do you think?

**Comment by gabizou** [comment]
Well Im closing this since we talked over how things work now with the DeckArrayManager (kinda unsused at this moment) and the Deck.
