### ISSUE TITLE
Game doesn't restart or ask for restarting

### ISSUE THREAD

**Issue by gabizou** [AfterKraft/BlackJack#5]
When finishing a hand, the game ends, Make it so that it doesn't.

**Comment by Duffmancool** [comment]
Put the whole thing in a do while loop i and check if the player wants to continue with a message box or something:

boolean cont=true;

do{
/**
 *WHITE Jack Program
*/
string in=JOptionPane.showInputDialog("Continue?(y/n)");
if(in=="y")
  cont=true;
else
  cont=false;
}while (cont);

**Comment by gabizou** [comment]
We'll rewrite the game code for BlackJack to be a separate object from the Game Logic.

**Comment by Duffmancool** [comment]
WhiteJack*

**Comment by gabizou** [comment]
Closing issue until WhiteJack 0.2 is released (Game API rewrite complete and basic GUI working).
