### ISSUE TITLE
Logic Error

### ISSUE THREAD

**Issue by Duffmancool** [AfterKraft/BlackJack#6]
https://github.com/AfterKraft/BlackJack/blob/master/WhiteJack/src/com/whitejack/api/Player.java

line 60: 

public Card getCard() {

```
    return card[--cardCount];

}
```

I meant for this method to return what was just received, but this returns what was just received AND marks that card for deletion without changing handValue.  It decriments cardCount so the next card will overwrite that card and the handValue will be incorrect. the correct code should be:

line 60: 

public Card getCard() {

```
    return card[cardCount-1];

}
```

I meant this method to be possibly used to write a card counter. As a separate class.

**Comment by gabizou** [comment]
Fixed!
